const popupConfig = {
    popupSelector: '.popup',
    templateElementSelector: '.template',
    figureContentSelector: '.popup__figure',
    editButtonSelector: '.profile__edit-button',
    addButtonSelector: '.profile__add-button',
    editPopupSelector: '.popup_type_edit',
    addPopupSelector: '.popup_type_add',
    editFormSelector: '.popup__form_type_edit',
    addFormSelector: '.popup__form_type_add',
    nameFieldSelector: '.popup__input_type_name',
    postFieldSelector: '.popup__input_type_post',
    placeFieldSelector: '.popup__input_type_place',
    linkFieldSelector: '.popup__input_type_link',
    profileNameSelector: '.profile__name',
    profilePostSelector: '.profile__post',
    popupOpenedSelector: '.popup_opened',
    closeButtonSelector: '.popup__close',
    closeButtonClass: 'popup__close',
    popupOpenedClass: 'popup_opened',
    popupClass: 'popup',
    figurePopupSelector: '.popup_type_figure',
    figureImageSelector: '.popup__image',
    figureCaptionSelector: '.popup__caption'
}